### PR TITLE
Make Test take and store std::function objects instead of function pointers

### PR DESCRIPTION
**Pull request by wsmigaj**
The ``CASE`` macro returns an anonymous function, and it is possible to make it capture arbitrary variables by passing it to the macro's variable argument. However, the returned function cannot be passed to the constructor of ``eckit::Test`` because the latter takes a function pointer, and only non-capturing lambdas can be converted into function pointers. 

This change replaces the function pointer parameter of ``eckit::Test::Test()`` by a ``std::function<...>`` parameter. This makes it possible, for example, to conveniently register multiple tests executing the same code, but operating on different data (e.g. different sections in a YAML file). Example: 

```
void testMyFilter(const eckit::LocalConfiguration &conf) {
  // Test filter configured using the parameters in 'conf'...
}

class MyFilterTest : public oops::Test {
  void register_tests() const override {
    std::vector<eckit::testing::Test> &tests = eckit::testing::specification();
    for (const std::string &section : conf.keys())
    {
      const eckit::LocalConfiguration testConf(::test::TestEnvironment::config(), section);
      // The CASE macro creates an anonymous function capturing 'testConf' by value
      ts.emplace_back(CASE("ufo/MyFilter/" + section, testConf)
                      {
                        testMyFilter(testConf);
                      });
    }
}
```

I'd like to use this functionality in an upcoming pull request to https://github.com/JCSDA/ufo.

### CODE REVIEW

**Comment by rhoneyager** [comment]
@ytremolet Some approved OOPS/UFO PRs depend on this. Shall I merge?

**Comment by ytremolet** [comment]
Yes, but we should issue a PR to ECMWF, it would be nice to get their feedback and not diverge.

**Comment by rhoneyager** [comment]
Okay. @wsmigaj, could you also submit to ECMWF?

**Comment by wsmigaj** [comment]
Many thanks for merging! I've opened a PR in ecmwf/eckit.

**Pull request merged**
